### ISSUE TITLE
AWS and Netlify still failing

### ISSUE THREAD

**Issue by siakaramalegos** [andydavies/http2-prioritization-issues#13]
**Please include server / CDN, and browser in issue title**

### Summary
Hi there, thanks for building this! Just came across it and thought I would re-run some to see if they had changed. AWS and Netlify (I use both so was curious) still look like they are failing. I don't mind making a PR myself - just let me know if you want me to replace the date links with the new reports and updated date or if you want to keep historical runs too somehow.

### Server / CDN etc.
Which server / CDN etc does this issue apply to?
AWS, Netlify

### Browser
What browsers did you test with?
I re-ran the same tests linked, so Chrome.

### Link to WebPageTest result
If you tested  using WebPageTest please add a link to the relevant result(s).
- AWS: https://www.webpagetest.org/result/191125_C2_29cc73b3b620e8394350a93bb65132a4/
- Netlify: https://www.webpagetest.org/result/191125_RF_82aade1007fd5495eaf80062272ea4f6/

### Link to  upstream bug report
If you're reported a bug to the relevant vendor, or project please add a link to it

**Comment by andydavies** [comment]
Thank you!

Needed to re-run the tests with 3G Fast profile (Chrome uses a different prioritisation mechanism on 3G connection) but having the URL to test made life easy
